apiVersion: v1
kind: Service
metadata:
  name: av-elasticsearch
  labels:
    component: av-elasticsearch
spec:
  type: LoadBalancer
  selector:
    component: av-elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
