apiVersion: v1
kind: ReplicationController
metadata:
  name: es
  labels:
    component: av-elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: av-elasticsearch
    spec:
      serviceAccount: av-elasticsearch
      containers:
      - name: av-es
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: elasticsearch
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "avesdb"
        - name: "DISCOVERY_SERVICE"
          value: "av-elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
